CREATE DATABASE IT8_DATABASE_PROJECT

SET DATEFORMAT dmy

USE IT8_DATABASE_PROJECT
GO

CREATE TABLE KHACHHANG
(
    USERNAME VARCHAR(20) NOT NULL,
    PASSWRD VARCHAR(20) NOT NULL,
    TENKH NVARCHAR(60) NOT NULL,
    EMAIL VARCHAR(60) NOT NULL,
    SDT VARCHAR(15) NOT NULL,
	SODU MONEY DEFAULT 0,
    GTINH BIT NOT NULL, -- 0: female, 1: male
    CONSTRAINT CS_PK_KHACHHANG PRIMARY KEY(USERNAME)
)
CREATE TABLE SANTHETHAO
(
    MASANTT VARCHAR(10) NOT NULL,
    MONTHETHAO VARCHAR(40) NOT NULL,
    TENSANTT VARCHAR(50) NOT NULL,
    GTSANG MONEY NOT NULL,
    GTTRUA MONEY NOT NULL,
    GTTOI MONEY NOT NULL,
    CONSTRAINT CS_PK_SANTHETHAO PRIMARY KEY(MASANTT)
)
CREATE TABLE HOADON
(
    MAHD VARCHAR(10) NOT NULL,
    USERNAME VARCHAR(20) NOT NULL,
    NGTTOAN DATE NOT NULL,
    TRIGIA MONEY NOT NULL,
    CONSTRAINT CS_PK_HOADON PRIMARY KEY(MAHD)
)
CREATE TABLE CTHD
(
    MAHD VARCHAR(10) NOT NULL,
    NGHDHLUC DATE NOT NULL,
	KHUNGGIO VARCHAR(10) NOT NULL, -- Có thể đặt nhiều khung giờ trong 1 sân, lưu theo dạng [khung1]+[khung2]+...+[khungN]_[tgian sân 2]_[tgian sân 3]
	SANDAT VARCHAR(3) DEFAULT 000,
    CONSTRAINT CS_PK_CTHD PRIMARY KEY(MAHD)
)
GO

ALTER TABLE HOADON
ADD CONSTRAINT PK_KHACHHANG_TO_FK_HOADON
FOREIGN KEY(USERNAME) REFERENCES KHACHHANG(USERNAME)

ALTER TABLE CTHD
ADD CONSTRAINT PK_HOADON_TO_FK_CTHD
FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD)

ALTER TABLE CTHD
ADD CONSTRAINT PK_SANTHETHAO_TO_FK_CTHD
FOREIGN KEY(MASANTT) REFERENCES SANTHETHAO(MASANTT)